// Add your dependencies here

dependencies {
    compile("com.github.GTNewHorizons:Avaritia:1.99:dev")
    compile("com.github.GTNewHorizons:WanionLib:1.10.1:dev")
    implementation('com.github.GTNewHorizons:NotEnoughItems:2.8.125-GTNH:dev')
    compileOnly("com.github.GTNewHorizons:inventory-tweaks:1.7.1:dev") {
        transitive = false
    }

    // For testing
    compileOnly("com.github.GTNewHorizons:Horizon-QA:0.13.1:dev")
    compileOnly("com.github.GTNewHorizons:Applied-Energistics-2-Unofficial:rv3-beta-1033-GTNH:dev")
    compileOnly('com.github.GTNewHorizons:GT5-Unofficial:5.09.54.80:dev') { transitive = false }
    compileOnly(rfg.deobf('curse.maven:mekanism-268560:2475797')) // https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2475797
    compileOnly('net.industrial-craft:industrialcraft-2:2.2.828-experimental:api')
    compileOnly('curse.maven:rotarycraft-235596:4721191')

    //runtimeOnlyNonPublishable("com.github.GTNewHorizons:Horizon-QA:0.13.1:dev")
    //runtimeOnlyNonPublishable("com.github.GTNewHorizons:Applied-Energistics-2-Unofficial:rv3-beta-1033-GTNH:dev")

}
